# ==================================================
#  Kitty Configuration
#  Copyright (c) 2025 chocopndn
#  GitHub: https://github.com/chocopndn
# ==================================================



# ==============================
#  Colors
# ==============================

background  #282828
foreground  #d4be98

## Normal Colors
color0  #3c3836
color1  #ea6962
color2  #a9b665
color3  #d8a657
color4  #7daea3
color5  #d3869b
color6  #89b482
color7  #d4be98

## Bright Colors
color8  #3c3836
color9  #ea6962
color10 #a9b665
color11 #d8a657
color12 #7daea3
color13 #d3869b
color14 #89b482
color15 #d4be98

# ==============================
#  Window Padding
# ==============================

window_padding_width  10
window_padding_height 10

# ==============================
#  Fonts
# ==============================

font_family   JetBrainsMono Nerd Font
font_size     11.5
bold_font     JetBrainsMono Nerd Font Bold
italic_font   JetBrainsMono Nerd Font Italic
